# Generated by Django 4.0.3 on 2022-05-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nationality', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authorName', models.CharField(default='', max_length=50)),
                ('bornDate', models.DateField(blank=True, null=True)),
                ('nationality', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='nationality.nationality')),
            ],
        ),
    ]
